const state = { programs: [], students: [], rosters: [] }; let dataDirectory = ''; let currentView = 'dashboard';
const labels = { programs:['프로그램 코드','프로그램명'], students:['학생 코드','학년','반','번호','이름'], rosters:['부서','학년','반','번호','이름'] };
const fields = { programs:['programCode','programName'], students:['studentCode','grade','classNo','number','name'], rosters:['department','grade','classNo','number','name'] };
const viewMeta = {dashboard:['대시보드','신청 양식 생성 현황을 확인합니다.'],programs:['프로그램 정보','프로그램 코드와 프로그램명을 관리합니다.'],students:['학생 정보','학생 코드와 학반 정보를 관리합니다.'],rosters:['부서별 학생 명단','부서별 수강생 명단을 관리합니다.'],matching:['매칭 결과','프로그램 및 학생 코드 매칭 상태를 검토합니다.'],settings:['데이터 저장 설정','개인정보 데이터가 저장되는 로컬 폴더를 관리합니다.']};

function key(v){return String(v??'').trim().replace(/\s+/g,'').toLowerCase()} function studentKey(x){return [x.grade,x.classNo,x.number,x.name].map(key).join('|')}
function getMatches(){
  const pMap=new Map(),sMap=new Map(),pDup=new Set(),sDup=new Set();
  state.programs.forEach(p=>{const k=key(p.programName);if(pMap.has(k))pDup.add(k);else pMap.set(k,p)});
  state.students.forEach(s=>{const k=studentKey(s);if(sMap.has(k))sDup.add(k);else sMap.set(k,s)});
  return state.rosters.map((r,i)=>{const pk=key(r.department),sk=studentKey(r),p=pMap.get(pk),s=sMap.get(sk);const errors=[];if(!p)errors.push('프로그램 미매칭');if(pDup.has(pk))errors.push('프로그램 중복');if(!s)errors.push('학생 미매칭');if(sDup.has(sk))errors.push('학생 중복');return {index:i+1,roster:r,program:p,student:s,errors,status:errors.length?'error':'ok'}});
}
async function persist(){await window.desktop.saveData(state)} function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function switchView(view){currentView=view;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#pageTitle').textContent=viewMeta[view][0];document.querySelector('#pageDesc').textContent=viewMeta[view][1];render()}
function render(){const c=document.querySelector('#content');if(currentView==='dashboard')c.innerHTML=dashboard();else if(['programs','students','rosters'].includes(currentView))c.innerHTML=dataView(currentView);else if(currentView==='matching')c.innerHTML=matchingView();else c.innerHTML=settingsView();bindView()}
function dashboard(){const m=getMatches(),ok=m.filter(x=>x.status==='ok').length;return `<div class="cards"><div class="card"><div class="label">프로그램</div><div class="value">${state.programs.length}</div><div class="sub">등록된 프로그램</div></div><div class="card"><div class="label">학생</div><div class="value">${state.students.length}</div><div class="sub">학생 코드 등록</div></div><div class="card"><div class="label">수강 신청</div><div class="value">${state.rosters.length}</div><div class="sub">부서별 명단 전체</div></div><div class="card"><div class="label">정상 매칭</div><div class="value">${ok}</div><div class="sub">오류 ${m.length-ok}건</div></div></div><div class="panel"><div class="panel-title"><h2>작업 순서</h2></div><div class="steps"><div class="step"><b>1. 프로그램 정보</b><span>코드와 프로그램명을 불러옵니다.</span></div><div class="step"><b>2. 학생 정보</b><span>학생 코드와 학반 정보를 불러옵니다.</span></div><div class="step"><b>3. 부서별 명단</b><span>실제 수강생 명단을 불러옵니다.</span></div><div class="step"><b>4. 양식 받기</b><span>오류 확인 후 신청 파일을 생성합니다.</span></div></div></div><div class="panel"><div class="panel-title"><h2>매칭 요약</h2><button class="secondary" data-go="matching">상세 확인</button></div>${m.length?`<table><thead><tr><th>구분</th><th>건수</th></tr></thead><tbody><tr><td>정상 매칭</td><td>${ok}</td></tr><tr><td>확인 필요</td><td>${m.length-ok}</td></tr></tbody></table>`:'<div class="empty">부서별 학생 명단을 등록하면 매칭 결과가 표시됩니다.</div>'}</div>`}
function dataView(kind){const rows=state[kind],f=fields[kind],l=labels[kind];return `<div class="panel"><div class="panel-title"><h2>데이터 입력</h2><div class="actions"><button class="ghost" data-template="${kind}">입력 양식 받기</button><button class="secondary" data-import="${kind}">엑셀 불러오기</button><button class="danger" data-clear="${kind}">전체 삭제</button></div></div><form id="addForm" class="form-grid">${l.map((x,i)=>`<input name="${f[i]}" placeholder="${x}" required>`).join('')}<button class="primary" type="submit">직접 추가</button></form><div class="toolbar"><div class="summary">총 ${rows.length}건</div><input id="search" placeholder="표 안에서 검색"></div><div id="tableWrap">${dataTable(kind,rows)}</div></div>`}
function dataTable(kind,rows){const f=fields[kind],l=labels[kind];if(!rows.length)return '<div class="empty">등록된 데이터가 없습니다.</div>';return `<table><thead><tr><th>No</th>${l.map(x=>`<th>${x}</th>`).join('')}<th>관리</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td>${f.map(x=>`<td>${escapeHtml(r[x])}</td>`).join('')}<td><button class="danger" data-delete="${kind}" data-id="${r.id}">삭제</button></td></tr>`).join('')}</tbody></table>`}
function matchingView(){const m=getMatches(),ok=m.filter(x=>x.status==='ok');return `<div class="cards"><div class="card"><div class="label">전체 신청</div><div class="value">${m.length}</div></div><div class="card"><div class="label">정상</div><div class="value">${ok.length}</div></div><div class="card"><div class="label">확인 필요</div><div class="value">${m.length-ok.length}</div></div><div class="card"><div class="label">출력 가능</div><div class="value">${ok.length}</div></div></div><div class="panel"><div class="panel-title"><h2>상세 매칭 결과</h2><button class="primary" id="exportMatch">정상 데이터 신청 양식 받기</button></div>${m.length?`<table><thead><tr><th>No</th><th>부서</th><th>학생</th><th>프로그램 코드</th><th>학생 코드</th><th>상태</th></tr></thead><tbody>${m.map(x=>`<tr><td>${x.index}</td><td>${escapeHtml(x.roster.department)}</td><td>${escapeHtml(`${x.roster.grade}-${x.roster.classNo}-${x.roster.number} ${x.roster.name}`)}</td><td>${escapeHtml(x.program?.programCode||'-')}</td><td>${escapeHtml(x.student?.studentCode||'-')}</td><td><span class="status ${x.status}">${x.status==='ok'?'정상':x.errors.join(', ')}</span></td></tr>`).join('')}</tbody></table>`:'<div class="empty">부서별 학생 명단을 등록해 주세요.</div>'}</div>`}
function settingsView(){return `<div class="panel"><div class="panel-title"><h2>데이터 저장 폴더</h2></div><p>프로그램·학생·수강생 데이터는 아래 폴더에만 저장됩니다.</p><div class="path">${escapeHtml(dataDirectory)}</div><div class="actions"><button class="primary" id="chooseDir">저장 폴더 변경</button><button class="ghost" id="openDir">폴더 열기</button></div></div><div class="panel"><div class="panel-title"><h2>개인정보 보호</h2></div><p>인터넷이나 외부 서버로 데이터를 전송하지 않습니다. 생성한 신청 파일과 데이터 폴더의 접근 권한은 사용자가 직접 관리해 주세요.</p></div>`}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function bindView(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));document.querySelectorAll('[data-import]').forEach(b=>b.onclick=()=>importExcel(b.dataset.import));document.querySelectorAll('[data-template]').forEach(b=>b.onclick=async()=>{if(await window.desktop.downloadTemplate(b.dataset.template))toast('입력 양식을 저장했습니다.')});document.querySelectorAll('[data-clear]').forEach(b=>b.onclick=async()=>{if(confirm('이 탭의 데이터를 모두 삭제할까요?')){state[b.dataset.clear]=[];await persist();render();toast('전체 데이터를 삭제했습니다.')}});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const k=b.dataset.delete;state[k]=state[k].filter(x=>x.id!==b.dataset.id);await persist();render()});const form=document.querySelector('#addForm');if(form)form.onsubmit=async e=>{e.preventDefault();const kind=currentView,obj={id:crypto.randomUUID()};new FormData(form).forEach((v,k)=>obj[k]=String(v).trim());state[kind].push(obj);await persist();render();toast('데이터를 추가했습니다.')};const search=document.querySelector('#search');if(search)search.oninput=()=>{const q=key(search.value);document.querySelector('#tableWrap').innerHTML=dataTable(currentView,state[currentView].filter(r=>Object.values(r).some(v=>key(v).includes(q))));bindDeleteOnly()};document.querySelector('#exportMatch')?.addEventListener('click',exportFile);document.querySelector('#chooseDir')?.addEventListener('click',async()=>{const p=await window.desktop.chooseDataDirectory(state);if(p){dataDirectory=p;render();toast('저장 폴더를 변경했습니다.')}});document.querySelector('#openDir')?.addEventListener('click',()=>window.desktop.openDataDirectory())}
function bindDeleteOnly(){document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const k=b.dataset.delete;state[k]=state[k].filter(x=>x.id!==b.dataset.id);await persist();render()})}
async function importExcel(kind){try{const rows=await window.desktop.importExcel(kind);if(!rows)return;if(state[kind].length&&!confirm(`기존 ${state[kind].length}건을 삭제하고 새 데이터 ${rows.length}건으로 바꿀까요?`))return;state[kind]=rows;await persist();render();toast(`${rows.length}건을 불러왔습니다.`)}catch(e){alert(`엑셀 파일을 불러오지 못했습니다.\n\n${e.message}`)}}
async function exportFile(){const ok=getMatches().filter(x=>x.status==='ok').map(x=>({programCode:x.program.programCode,programName:x.program.programName,studentCode:x.student.studentCode,studentName:x.student.name}));if(!ok.length)return alert('정상 매칭된 데이터가 없습니다.');if(await window.desktop.exportResult(ok))toast(`${ok.length}건의 신청 양식을 저장했습니다.`)}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelector('#exportTop').onclick=exportFile;
window.desktop.onAppVersion(version=>{document.querySelector('#appVersion').textContent=`v${version}`});
window.desktop.onUpdateStatus(status=>{
  const panel=document.querySelector('#updatePanel'),bar=document.querySelector('#updateBar'),percent=document.querySelector('#updatePercent'),message=document.querySelector('#updateMessage');
  if(status.state==='downloading'){
    const value=Math.round(status.percent||0);panel.hidden=false;bar.style.width=`${value}%`;percent.textContent=`${value}%`;message.textContent=value<100?'새 버전을 받고 있습니다.':'다운로드를 마무리하고 있습니다.';
  }else if(status.state==='downloaded'){
    panel.hidden=false;bar.style.width='100%';percent.textContent='100%';message.textContent='다운로드가 완료되었습니다.';
  }else if(status.state==='ready-later'){
    panel.hidden=true;toast('앱을 종료하면 업데이트가 설치됩니다.');
  }else if(status.state==='error'){
    panel.hidden=true;toast(status.message||'업데이트 중 오류가 발생했습니다.');
  }
});
(async()=>{const loaded=await window.desktop.loadData();Object.assign(state,loaded.data);dataDirectory=loaded.dataDirectory;render()})();
